[General]                              
Background="Backgrounds/vi-arcane.jpg"                                            
DimBackgroundImage="0.3"                                                         
ScaleImageCropped="true"                                                         
ScreenWidth="1920"                                                               
ScreenHeight="1080"                                                            
FullBlur="false"   
PartialBlur="true"                                                               
BlurRadius="60"   
HaveFormBackground="true"                                                        
FormPosition="center"                                                          
BackgroundImageHAlignment="center"
BackgroundImageVAlignment="center"
MainColor="#cdd6f4"               
AccentColor="#cba6f7"
BackgroundColor="#1e1e2e"                                                        
OverrideLoginButtonTextColor="#1e1e2e"
InterfaceShadowSize="6"                                                          
InterfaceShadowOpacity="0.6"                                                   
RoundCorners="20"           
ScreenPadding="0"                                                                
Font="Noto Sans" 
FontSize=""                                                                      
ForceLastUser="true"                                                           
ForcePasswordFocus="true"
ForceHideCompletePassword="false"
ForceHideVirtualKeyboardButton="false"
ForceHideSystemButtons="false"                                                   
AllowEmptyPassword="false"    
AllowBadUsernames="false"                                                        
HourFormat="HH:mm"                                                             
DateFormat="dddd, d de MMMM"
HeaderText="Bem-vindo"
